// <auto-generated />
using System;
using MyACTS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MyACTS.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20230201_000009_CreateMessagesStatusTable")]
partial class CreateMessagesStatusTable
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) {
        modelBuilder.Entity("MyACTS.Models.Entities.MessageStatus", entity =>
        {
            entity.ToTable("messages_status", (string) null);

            entity.Property<int>("MessageId")
                .HasColumnType("int")
                .HasColumnName("id_message");

            entity.Property<int>("UserId")
                .HasColumnType("int")
                .HasColumnName("id_user");

            entity.Property<string>("Status")
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("status");

            entity.Property<DateTime?>("Timestamp")
                .HasColumnType("datetime")
                .HasColumnName("timestamp");

            entity.Property<string>("CurrentSessionToken")
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("current_session_token");

            entity.HasKey("MessageId", "UserId")
                .HasName("PK__messages_status")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            //entity.HasIndex(new[] { "MessageId" }, "IDX__messages_status__id_message")
            //    .HasDatabaseName("IDX__messages_status__id_message");
            //entity.HasIndex(new[] { "UserId" }, "IDX__messages_status__id_user");
        });
    }
}

