// <auto-generated />
using System;
using MyACTS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MyACTS.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20230201_000006_CreateServicesTable")]
partial class CreateServicesTable
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("MyACTS.Models.Entities.Service", entity =>
        {
            entity.ToTable("services", (string) null);

            entity.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .HasColumnName("id_service");

            entity.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("name");

            entity.Property<string>("Description")
                .HasColumnType("text")
                .HasColumnName("description");

            entity.Property<string>("Url")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("url");

            entity.Property<string>("ImageUrl")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("image_url");

            entity.Property<byte[]>("Icon")
                .HasColumnType("blob")
                .HasColumnName("icon");

            entity.HasKey("Id")
                .HasName("PK__services");

            entity.HasIndex(new[] { "Name" }, "IDX__services__name")
                .IsUnique()
                .HasDatabaseName("IDX__services__name");
        });
    }
}

