// <auto-generated />
using System;
using MyACTS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MyACTS.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20230201_000001_CreatePermissionsTable")]
partial class CreatePermissionsTable
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("MyACTS.Models.Entities.Permission", entity =>
        {
            entity.ToTable("permissions", (string) null);

            entity.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .HasColumnName("id_permission");

            entity.Property<string>("Name")
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasColumnName("name");

            entity.Property<string>("Description")
                .HasColumnType("text")
                .HasColumnName("description");

            entity.Property<string>("Action")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("action");

            entity.Property<string>("Type")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("type");

            entity.Property<string>("Target")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("target");

            entity.Property<int?>("TargetId")
                .HasColumnType("int")
                .HasColumnName("id_target");

            entity.HasKey("Id")
                .HasName("PK__permissions");

            entity.HasIndex(new[] { "Name" }, "IDX__permissions__name")
                .IsUnique();
        });
    }
}

