// <auto-generated />
using System;
using MyACTS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MyACTS.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20230201_000003_CreateUsersTable")]
partial class CreateUsersTable
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("MyACTS.Models.Entities.User", entity =>
        {
            entity.ToTable("users", (string) null);

            entity.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .HasColumnName("id_user");

            entity.Property<string>("UserName")
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasColumnName("user_name");

            entity.Property<string>("FullName")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("full_name");

            entity.Property<string>("Email")
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasColumnName("email");

            entity.Property<string>("PhoneNumber")
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("phone_number");

            entity.Property<DateOnly?>("DateOfBirth")
                .HasColumnType("date")
                .HasColumnName("date_of_birth");

            entity.Property<string>("PasswordHash")
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("password_hash");

            entity.HasKey("Id")
                .HasName("PK__users");

            entity.HasIndex(new[] { "UserName" }, "IDX__users__user_name")
                .IsUnique();

            entity.HasIndex(new[] { "Email" }, "IDX__users__email")
                .IsUnique();
        });
    }
}
