// <auto-generated />
using System;
using MyACTS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MyACTS.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20230201_000005_CreateUsersRolesTable")]
partial class CreateUserRolesTable
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("UserRole", entity =>
        {
            entity.ToTable("user_roles", (string) null);

            entity.Property<int>("UserId")
                .HasColumnName("id_user")
                .HasColumnType("int");

            entity.Property<int>("RoleId")
                .HasColumnName("id_role")
                .HasColumnType("int");

            entity.HasKey("UserId", "RoleId")
                .HasName("PK__user_roles")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity.HasIndex(new[] { "UserId" }, "IDX__user_roles__id_user");

            entity.HasIndex(new[] { "RoleId" }, "IDX__user_roles__id_role");
        });
    }
}

