// <auto-generated />
using System;
using MyACTS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MyACTS.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20230201_000010_CreateEventsStatusTable")]
partial class CreateEventsStatusTable
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("MyACTS.Models.Entities.EventsStatus", entity =>
        {
            entity.ToTable("events_status", (string) null);

            entity.Property<int>("EventId")
                .HasColumnType("int")
                .HasColumnName("id_event");

            entity.Property<int>("UserId")
                .HasColumnType("int")
                .HasColumnName("id_user");

            entity.Property<string>("Status")
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("status");

            entity.Property<DateTime?>("Timestamp")
                .HasColumnType("datetime")
                .HasColumnName("timestamp");

            entity.Property<string>("CurrentSessionToken")
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("current_session_token");

            entity.HasKey("EventId", "UserId")
                .HasName("PK__events_status")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity.HasIndex(new[] { "EventId" }, "IDX__events_status__id_event");
            entity.HasIndex(new[] { "UserId" }, "IDX__events_status__id_user");
        });

    }
}

