// <auto-generated />
using System;
using MyACTS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MyACTS.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20230201_000002_CreateRolesTable")]
partial class CreateRolesTable {

    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("MyACTS.Models.Entities.Role", entity =>
        {
            entity.ToTable("roles", (string) null);

            entity.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .HasColumnName("id_role");

            entity.Property<string>("Description")
                .HasColumnType("text")
                .HasColumnName("description");

            entity.Property<string>("Name")
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasColumnName("name");

            entity.HasKey("Id")
                .HasName("PK__roles");

            entity.HasIndex(new[] { "Name" }, "IDX__roles__name")
                .IsUnique()
                .HasDatabaseName("IDX__roles__name");
        });
    }
}

