// <auto-generated />
using System;
using MyACTS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MyACTS.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20230201_000008_CreateEventsTable")]
partial class CreateEventsTable
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("MyACTS.Models.Entities.Event", entity =>
        {
            entity.ToTable("events", (string) null);

            entity.Property<int>("Id")
                .HasColumnType("int")
                .HasColumnName("id_event");

            entity.Property<string>("Subject")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("subject");

            entity.Property<string>("Body")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("body");

            entity.Property<DateTime>("Start")
                .HasColumnType("datetime")
                .HasColumnName("start");

            entity.Property<DateTime>("End")
                .HasColumnType("datetime")
                .HasColumnName("end");

            entity.Property<string>("ActionText")
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("action_text");

            entity.Property<string>("ActionUrl")
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("action_url");

            entity.Property<int>("Source")
                .HasColumnType("int")
                .HasColumnName("source");

            entity.Property<string>("Target")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("varchar(255)")
                .HasColumnName("target");

            entity.Property<int?>("TargetId")
                .HasColumnType("int")
                .HasColumnName("id_target");

            entity.HasKey("Id")
                .HasName("PK__events");

            entity.HasOne("MyACTS.Models.Entities.User", "User")
                .WithMany("Events")
                .HasForeignKey("Source")
                .IsRequired()
                .HasConstraintName("FK__events__users__source");

            entity.HasIndex(new[] { "Source" }, "IDX__events__source");
            entity.HasIndex(new[] { "Target" }, "IDX__events__target");
            entity.HasIndex(new[] { "TargetId" }, "IDX__events__id_target_");

            entity.Navigation("User");
        });

    }
}

